<?php

use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputDefinition;
use Symfony\Component\Console\Input\InputOption;

class ConsoleApplicationZf extends \Symfony\Component\Console\Application
{
    protected function getDefaultInputDefinition()
    {
        $inputDefinition = parent::getDefaultInputDefinition(); // TODO: Change the autogenerated stub

        $inputDefinition->addOption(new InputOption("env", null, InputOption::VALUE_REQUIRED, "Environement d'execution", null));

        return $inputDefinition;
    }

}